name: "Run on Default Branch - Add Utilities & App Inspect"

on:
  push:
    branches:
      - 'develop'

  workflow_dispatch:

jobs:
  pre-release:
    name: "Run on Default Branch - Add Utilities & App Inspect"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v2.7
        with:
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_utilities: "whats_in_the_app, logger, splunk_python_sdk"
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          logger_log_files_prefix: "greenalert"
          logger_sourcetype: "greenalert:logs"
