name: "Build, Splunkbase App Inspect, App Utilities"

on:
  push:
    branches:
      - 'develop'

  workflow_dispatch:


jobs:
  on_main:
    name: "Build, Splunkbase App Inspect, App Utilities"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v6
        with:
          to_make_permission_changes: true
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_utilities: "whats_in_the_app, logger"
          logger_log_files_prefix: "greenalert"
          logger_sourcetype: "greenalert:logs"
          python_requirements_file: "lib/requirements.txt"
        env:
          SPLUNK_APP_ACTION_1: "rm -f CLAUDE.md"
