name: "On PR - Generate Build"

on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:

jobs:
  pre-release:
    name: "On PR - Generate Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v2
        with:
          app_dir: "green_alerts_app"
          is_app_inspect_check: false
