name: "Build and Local App Inspect"

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  on_pr:
    name: "Build and Local App Inspect"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v7
        with:
          local_app_inspect: true
          to_make_permission_changes: true
          python_requirements_file: "lib/requirements.txt"
        env:
          SPLUNK_APP_ACTION_1: "rm -f CLAUDE.md"
